[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 50
style = "bold green"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 15
style = "bold red"

[character]
symbol = "â€º"
error_symbol = "âœ—"
use_symbol_for_status = true
vicmd_symbol = "Â»"

[cmd_duration]
min_time = 2000
prefix = "ğŸ•‘ "

[directory]
truncation_length = 0
fish_style_pwd_dir_length = 1
prefix = ""

[git_branch]
symbol = "ğŸŒ± "

[git_state]
rebase = "âš¾"
merge = "ğŸš§"
revert = "ğŸ‰"
bisect = "âœ‚"
am = "ğŸ“®"
am_or_rebase = "ğŸ“®âš¾"
cherry_pick = "ğŸ’"

[git_status]
conflicted = "ğŸ”¥"
ahead = "ğŸ‘"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "ğŸ­"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[hostname]
ssh_only = false
prefix = "âŸª"
suffix = "âŸ«\n"
disabled = false

[memory_usage]
disabled = false
show_percentage = true
show_swap = false

[package]
symbol = "ğŸ "

[username]
sho_always = true

[custom.home_date_status]
command = "git --git-dir=$HOME/.baredotfiles/ --work-tree=$HOME status --short;"
when = """ test "$HOME" = "$PWD" """
prefix = "\n"
style = ""
w
